[project]
name = "hello-world"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
 "eclipse-zenoh>=1.7.1",
]

[project.scripts]
hello = "hello_world:hello"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
